[project]
name = "sheetmerge"
version = "0.1.0"
description = "A short script to match two CSVs of students."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chardet>=5.2.0",
    "pandas>=2.2.3",
]

[tool.uv]
dev-dependencies = [
    "pyinstaller>=6.11.1",
]
