name: Build Windows Executable

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Build windows .exe
        run: |
          .venv\Scripts\Activate.ps1
          pyinstaller --noconfirm --onefile --clean --name "Student Matcher" "main.py"

      - uses: actions/upload-artifact@v4
        with:
          name: "Student Matcher.exe"
          path: dist/"Student Matcher.exe"
          if-no-files-found: error

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: "Student Matcher.exe"
          path: ./
      - name: Generate release timestamp
        id: timestamp
        run: echo "timestamp=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT
      - uses: softprops/action-gh-release@v2
        with:
          files: "./Student Matcher.exe"
          tag_name: "v${{ steps.timestamp.outputs.timestamp }}"
